name: registerapp
description: "A new Ozonteck project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dots_indicator: ^3.0.0
  get_storage: ^2.1.1
  flutter_iconly: ^1.0.2
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  getwidget: ^4.0.0
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^9.0.1
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


